### ISSUE TITLE
Video call unusable

### ISSUE THREAD

**Issue by pciverson** [boostlingo/boostlingo-android#5]
When you are on the phone, you are in direct contact, you do not see the screen, the bottom is the information.
2022-10-15 20:56:39.001 14268-14268 CameraManagerGlobal     com.boostlingo.android.quickstart    I  Connecting to camera service
2022-10-15 20:56:39.063 14268-14268 BoostlingoSDK           com.boostlingo.android.quickstart    E  handleHubError:
                                                                                                    java.lang.NullPointerException
                                                                                                    	at com.boostlingo.android.CameraCapturerCompat.<init>(CameraCapturerCompat.kt:167)
                                                                                                    	at com.boostlingo.android.BLVideoCall.createAudioAndVideoTracks(BLVideoCall.kt:318)
                                                                                                    	at com.boostlingo.android.BLVideoCall.connect$boostlingo_release(BLVideoCall.kt:109)
                                                                                                    	at com.boostlingo.android.BoostlingoSDK.handleCallHubEvent$lambda-28(BoostlingoSDK.kt:344)
                                                                                                    	at com.boostlingo.android.BoostlingoSDK.$r8$lambda$WG4-kj2ArbaQl7AoHR4f3nxIR38(Unknown Source:0)
                                                                                                    	at com.boostlingo.android.BoostlingoSDK$$ExternalSyntheticLambda14.run(Unknown Source:4)
                                                                                                    	at com.boostlingo.android.BoostlingoSDK.mutateCall(BoostlingoSDK.kt:589)
                                                                                                    	at com.boostlingo.android.BoostlingoSDK.handleCallHubEvent(BoostlingoSDK.kt:341)
                                                                                                    	at com.boostlingo.android.BoostlingoSDK.$r8$lambda$Xz9cXWXGgcJAXU60_mFn9aQVuKA(Unknown Source:0)
                                                                                                    	at com.boostlingo.android.BoostlingoSDK$$ExternalSyntheticLambda19.accept(Unknown Source:4)
                                                                                                    	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
                                                                                                    	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
                                                                                                    	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
                                                                                                    	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6702)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by dkornev** [comment]
Hi @pciverson 
Thank you for creating this one.

Could you please provide me with more info about you Android device you are using? What is the device model and the OS running?

**Comment by dkornev** [comment]
The issue should be fixed in [v1.0.1](https://github.com/boostlingo/boostlingo-android/releases/tag/v1.0.1)
